<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scalar product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [1]:
import numpy as np

In [2]:
a = [-12, 16]
b = [12, 9]

In [5]:
#answer:
np.dot(a,b)

0

2. Compute the Hadamard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [9]:
#answer:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [ ]:
#desired output:
# np.array([[5,12],[21,32]])

3. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [11]:
# Add two matrices using a nested loop

X = [[1,2,3],
    [4,5,6],
    [7,8,9]]

Y = [[2,3,7],
    [1,4,9],
    [3,2,3]]

In [46]:
#answer:
A=[]
for i in range(len(X)):
        B=[]
        for j in range(len(X)):
              B.append(X[i][j] + Y[i][j])
        A.append(B)

#A[0,0] = X[0][0]+Y[0][0]
print(A)


[[3, 5, 10], [5, 9, 15], [10, 10, 12]]


In [ ]:
#desired output:
#[[3,5,10],
# [5,9,15],
# [10,10,12]]

4. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [58]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.

Thought process:
R = [[R11, R12, R13],
    [R21, R22, R23],
    [R31, R32, R33]]

R11 = X row 1 X Y col 1 = X11*Y11 + X12*Y21 + X13*Y31
R12 = X row 1 x Y col 2 = X11*Y12 + X12*Y22 + X13*Y32
R13 = X row 1 x Y col 3 = X11*Y13 + X12*Y23 + X13*Y33
X14 = X row 1 X Y col 4 = X11*Y14 + X12*Y24 + X13*Y34



In [117]:
#answer:
X_matrix = np.array(X)
Y_matrix = np.array(Y)

print("number of column X matrix :", X_matrix.shape[1])
print("number of column Y matrix :", Y_matrix.shape[1])
print(X_matrix)

R = []
for row in range(X_matrix.shape[1]):
    ## Make an empty list for each row
    T = []
    for col in range(Y_matrix.shape[1]):
        # define the integer variable
        b = 0
        for k in range(len(X_matrix)):
            a = X_matrix[row][k] * Y_matrix[k][col]
            b = b+a
        # Append the result into the row.
        T.append(b)
    R.append(T)

print(R)

number of column X matrix : 3
number of column Y matrix : 4
[[7 2 4]
 [3 9 5]
 [8 1 6]]
[[65, 72, 52, 80], [59, 70, 112, 85], [83, 80, 55, 99]]


In [ ]:
#desired output:
#[[65, 72, 52, 80],
# [59, 70, 112, 85],
# [83, 80, 55, 99]]

5. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use
> np.linalg.det

In [184]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [222]:
## from https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/

def determinant_recursive(A, total=0):
    # Section 1: store indices in list for row referencing
    indices = [i for i in range(len(matrix))]
    #indices = list(range(len(A)))
     
    # Section 2: when at 2x2 submatrices recursive calls end
    if len(A) == 2 and len(A[0]) == 2:
        val = A[0][0] * A[1][1] - A[1][0] * A[0][1]
        return val
 
    # Section 3: define submatrix for focus column and 
    #      call this function
    for fc in indices: # A) for each focus column, ...
        # find the submatrix ...
        As = A.copy() # B) make a copy, and ...
        As = As[1:] # ... C) remove the first row
        height = len(As) # D) 
 
        for i in range(height): 
            # E) for each remaining row of submatrix ...
            #     remove the focus column elements
            As[i] = As[i][0:fc] + As[i][fc+1:] 
 
        sign = (-1) ** (fc % 2) # F) 
        # G) pass submatrix recursively
        sub_det = determinant_recursive(As)
        # H) total all returns from recursion
        total += sign * A[0][fc] * sub_det 
 
    return total

determinant_recursive(matrix)

18

6. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use
> from numpy.linalg import inv

In [224]:
a = np.array([[1., 2.], [3., 4.]])

In [227]:
#answer:
from numpy.linalg import inv

a_inverse = np.linalg.inv(a)
print(a_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]




---



---



> > > > > > > > > © 2023 Institute of Data


---



---



